/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CpIcon: typeof import('./src/components/cpIcon.vue')['default']
    CpNavBar: typeof import('./src/components/cpNavBar.vue')['default']
    CpRadioBtn: typeof import('./src/components/cpRadioBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
